config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#index'
  get '/users/logout', to: 'users#logout'
  get '/users/login', to: 'users#login'
  post '/users/login', to: 'users#login'

  get '/users/register', to: 'users#register'
  post '/users/register', to: 'users#register'

  resources :posts
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :post, length: { minimum: 50, maximum: 255 }
    enum status: { public_status: 0 , private_status: 1 }
end

app/models/user.rb
class User < ApplicationRecord
    validates_presence_of :email, :password
    validates_uniqueness_of :email

    
    def self.authenticate(args={})
        self.where(email: args[:email], password: args[:password]).empty? ? false: true 
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @posts = Post.where(status:"public_status")
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :login_required 

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = session[:user_id]
    # @post.status = params[:post][:status].to_i
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  private
    # check login
    def login_required
      if session[:user_id]
        user = User.where("id", session[:user_id]).first
      end
          
      if !user
        reset_session
        flash[:notice] = "You must be logged in to acess this location."
        redirect_to "/users/login"
      end
    end


    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :post, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # new user registration
  def register
    @user  = User.new
    if request.method == "POST"
      user = params[:user]
      @user.email = user[:email]
      @user.password = user[:password]
      if @user.valid?
        @user.save
        flash[:notice] = "registration successful. You may log in."
        redirect_to "/users/login"
      end
    end 

  end


  def login
    if session[:user_id]
      redirect_to "/posts"
    end

    if request.method == "POST" && !params.empty?
      @user = User.where(email: params[:email], password: params[:password]).first
      if @user
        session[:user_id] = @user.id
        session[:email] = @user.email
        flash[:notice] = "Login successful."
        redirect_to "/posts"
      else
        flash[:notice] = "login failed."
      end
    end

  end

  def logout
    if session[:user_id]
      reset_session
      flash[:notice] = "You are logged out."
    end
  
    redirect_to "/users/login"
  
  end 

  private

  def post_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Post</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user.email %></td>
        <td><%= post.post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= render partial: "shared/links" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocha</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="field">
    <%= form.label :post %>
    <%= form.text_area :post, size: "70x5" %>
  </div>
  <div class="field">
  <%= form.label :status %>
  <%= form.select  :status , options_for_select(Post.statuses.map {|key,| [key.titleize, key]}, post.status) %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.post %></td>
        <Td><%= post.status.titleize %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= render partial: "shared/links" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post.post %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_links.html.erb
<% if session[:user_id] %>
<%= link_to  "your posts listings" , "/posts" %>
<%= link_to 'New Post', "/posts/new" %>
<%= link_to 'Logout', "/users/logout" %>
<% else %>
<%= link_to 'Register', "/users/register" %>
<%= link_to 'Login', "/users/login" %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(url: url, model: user) do |f| %>

  <% if user.errors.any? %>
    <ul>
      <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>


  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password  %>
  </div>
  
  <%= f.submit button_value %>

  <% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>Twitter handle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.twitter_handle %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<div class="headline">Login</div>

<%= form_with(url: "/users/login") do |f| %>

  
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
  
    <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password  %>
    </div>
    
    <%= f.submit "Login" %>
    <div>
      <%= link_to  "Register" ,"/users/register" %>
    </div>

<% end %>
  
  

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/register.html.erb
<div class="headline">Register</div>
 
<%= form_with(url: "/users/register", model: @user) do |f| %>

    <% if @user.errors.any? %>
      <ul>
        <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
        <% end %>
      </ul>
    <% end %>
  
  
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
  
    <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password  %>
    </div>
    
    <%= f.submit "Register" %>
  
    <div>
      <%= link_to  "Login" ,"/users/login" %>
    </div>
    <% end %>
  
  

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Twitter handle:</strong>
  <%= @user.twitter_handle %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>